### ISSUE TITLE
[help] what should i use base model for unet_vton? 

### ISSUE THREAD

**Issue by edith-wq** [lyc0929/OOTDiffusion-train#16]
I want to train the unet_vton model from scratch. 
when i put sd1.5 in unet_vton folder, the loss start at 0.1 ....  . I think it is wrong. 
![image](https://github.com/lyc0929/OOTDiffusion-train/assets/117714440/008f2c54-37f8-4d91-a9b6-fad2ab634010)
( i use this url, https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main/unet)
also the result is bad. 
![image](https://github.com/lyc0929/OOTDiffusion-train/assets/117714440/e146a6b7-87a9-47d8-8447-bce24d786a58)

can i get some help?

**Comment by zhangquanwei962** [comment]
> I want to train the unet_vton model from scratch. when i put sd1.5 in unet_vton folder, the loss start at 0.1 .... . I think it is wrong. !

1. the unet_vton and unet_grament is co-training, so have you setting the unet_grament weight? 2. the loss starts from 0.1, from my view,  it is right.

**Comment by edith-wq** [comment]
Yes, import SD1.5 models as initial models for unet_garm and unet_vton.

**Comment by edith-wq** [comment]
> > I want to train the unet_vton model from scratch. when i put sd1.5 in unet_vton folder, the loss start at 0.1 .... . I think it is wrong. !
> 
> 1. the unet_vton and unet_grament is co-training, so have you setting the unet_grament weight? 2. the loss starts from 0.1, from my view,  it is right.

Yes, import SD1.5 models as initial models for unet_garm and unet_vton....

**Comment by GeneralWhite** [comment]
![image](https://github.com/lyc0929/OOTDiffusion-train/assets/78407072/02c4e6f2-183d-4ce0-8b9d-3cbc20e56457)
Encountered the same problem
