### ISSUE TITLE
train result (100epoch) is not good. where is it wrong?

### ISSUE THREAD

**Issue by failbetter77** [lyc0929/OOTDiffusion-train#22]
I'm training from initial. 

the result is very not good. 
I don't know where I went wrong.

train scheduler :
{
    "_class_name": "PNDMScheduler",
    "_diffusers_version": "0.6.0",
    "beta_end": 0.012,
    "beta_schedule": "scaled_linear",
    "beta_start": 0.00085,
    "num_train_timesteps": 1000,
    "set_alpha_to_one": false,
    "skip_prk_steps": true,
    "steps_offset": 1,
    "trained_betas": null,
    "clip_sample": false
  }

clip-vit-large-patch14, preprocessor_config.json
{
  "crop_size": 224,
  "do_center_crop": true,
  "do_normalize": true,
  "do_resize": true,
  "feature_extractor_type": "CLIPFeatureExtractor",
  "image_mean": [
    0.48145466,
    0.4578275,
    0.40821073
  ],
  "image_std": [
    0.26862954,
    0.26130258,
    0.27577711
  ],
  "resample": 3,
  "size": 224
}

![image](https://github.com/lyc0929/OOTDiffusion-train/assets/100422523/242b4e66-d707-4dd4-8954-cf8c863c883a)

**Comment by GeneralWhite** [comment]
Hello, what does the loss look like during your training process? I have only trained for a few dozen epochs so far, but found that the model did not converge. 
😕 😕

**Comment by failbetter77** [comment]
> Hello, what does the loss look like during your training process? I have only trained for a few dozen epochs so far, but found that the model did not converge. 😕 😕

start 0.1(0 epoch)~ drop near 0.02(100epoch) ,

**Comment by GeneralWhite** [comment]
![image](https://github.com/lyc0929/OOTDiffusion-train/assets/78407072/4eeb403e-890d-4152-9900-f1c692472436)
I have only trained for a dozen epochs so far. My loss has been oscillating around 0.02 but has not converged. I suspect that if I continue training for 100 epochs, the loss will still not converge and oscillating around 0.02. 🤔 🤔

**Comment by failbetter77** [comment]
> ![image](https://private-user-images.githubusercontent.com/78407072/324198178-4eeb403e-890d-4152-9900-f1c692472436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2Njc2NTAsIm5iZiI6MTcxMzY2NzM1MCwicGF0aCI6Ii83ODQwNzA3Mi8zMjQxOTgxNzgtNGVlYjQwM2UtODkwZC00MTUyLTk5MDAtZjFjNjkyNDcyNDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAyNDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMjAxODM3NzBjOGNmZjRjNGE5MmFjYzVkOGJiNDFkMDc5NjVhNWUwMzYyYjg5M2VmOTFiMGZkMzZlMWExYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qV5RrhiCR5O5Ca3P5laiEyEZFLCUqb-hKPjbBmbyJxo) I have only trained for a dozen epochs so far. My loss has been oscillating around 0.02 but has not converged. I suspect that if I continue training for 100 epochs, the loss will still not converge and oscillating around 0.02. 🤔 🤔


My graph is the same as yours. ;; how about your result? can you share it?

**Comment by GeneralWhite** [comment]
> > ![image](https://private-user-images.githubusercontent.com/78407072/324198178-4eeb403e-890d-4152-9900-f1c692472436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2Njc2NTAsIm5iZiI6MTcxMzY2NzM1MCwicGF0aCI6Ii83ODQwNzA3Mi8zMjQxOTgxNzgtNGVlYjQwM2UtODkwZC00MTUyLTk5MDAtZjFjNjkyNDcyNDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAyNDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMjAxODM3NzBjOGNmZjRjNGE5MmFjYzVkOGJiNDFkMDc5NjVhNWUwMzYyYjg5M2VmOTFiMGZkMzZlMWExYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qV5RrhiCR5O5Ca3P5laiEyEZFLCUqb-hKPjbBmbyJxo) I have only trained for a dozen epochs so far. My loss has been oscillating around 0.02 but has not converged. I suspect that if I continue training for 100 epochs, the loss will still not converge and oscillating around 0.02. 🤔 🤔
> 
> My graph is the same as yours. ;; how about your result? can you share it?

Sorry, I set up to save the model every 50 epochs, but I haven't reached 50 epochs yet. :disappointed::disappointed:  I will send you the results when I complete the training. 

Thank you for your help.

**Comment by sonnv174** [comment]
I'm trying to train on 2xA5000 (2x24GB) with batch-size = 1 but still be CUDA out of memory. Could you share your condition information (GPU, accelerate config, ... ) to train from the initial? 

I have set to train with LoRA and got the loss during 30 epochs similar to yours.

**Comment by GeneralWhite** [comment]
> I'm trying to train on 2xA5000 (2x24GB) with batch-size = 1 but still be CUDA out of memory. Could you share your condition information (GPU, accelerate config, ... ) to train from the initial?
> 
> I have set to train with LoRA and got the loss during 30 epochs similar to yours.

I attempted training with a 4x4090 GPU (24GB), but regardless of how I adjusted the parameters, I encountered an 'OOM' (Out of Memory) error. Now, I'm using A100 GPU for training this model.

**Comment by Sheldongg** [comment]
这结果也太差了

**Comment by sonnv174** [comment]
> I attempted training with a 4x4090 GPU (24GB), but regardless of how I adjusted the parameters, I encountered an 'OOM' (Out of Memory) error. Now, I'm using A100 GPU for training this model.

Oh, thanks for your reply. It's probably not possible to train this pipeline with the 24GB GPU.
