### ISSUE TITLE
The expanded size of the tensor (4) must match the existing size (8) at non-singleton dimension 1

### ISSUE THREAD

**Issue by GeneralWhite** [lyc0929/OOTDiffusion-train#5]
File "OOTDiffusion/run/ootd_train.py", line 206, in <module>
    conv_new.weight.data[:, :4] = unet_vton.conv_in.weight.data 
**RuntimeError: The expanded size of the tensor (4) must match the existing size (8) at non-singleton dimension 1**.  Target sizes: [320, 4, 3, 3].  Tensor sizes: [320, 8, 3, 3]

Sorry to bother you, I'm new to the diffusion model and don't know much about model training, I'm running the code with the above error, should I change new.weight[:, :4] to [:, :8] or is there something wrong with my unet_vton.conv_in?

tks!

**Comment by zhangquanwei962** [comment]
Hi, I see your problem. Please check out your diffusion model's version, it must be V1.5 or V1.4. I guess your diffusion model's version is the official OOTD diffusion model.

**Comment by Hankerlove** [comment]
> Hi, I see your problem. Please check out your diffusion model's version, it must be V1.5 or V1.4. I guess your diffusion model's version is the official OOTD diffusion model.
> 
> In addition, if I solve your concern, can you give this project a **star**, thank you.


I wonder that if my diffusion model in "/OOTDiffusion/checkpoints/ootd/ootd_hd/checkpoint-36000/" should be the original Stable Diffusion_v1.5 model, but not the official OOTD diffusion model

**Comment by lyc0929** [comment]
> > Hi, I see your problem. Please check out your diffusion model's version, it must be V1.5 or V1.4. I guess your diffusion model's version is the official OOTD diffusion model.
> > In addition, if I solve your concern, can you give this project a **star**, thank you.
> 
> I wonder that if my diffusion model in "/OOTDiffusion/checkpoints/ootd/ootd_hd/checkpoint-36000/" should be the original Stable Diffusion_v1.5 model, but not the official OOTD diffusion model

yes , if you want to train your own model,you should use SDv1-5 model as model input.

**Comment by Hankerlove** [comment]
> > > Hi, I see your problem. Please check out your diffusion model's version, it must be V1.5 or V1.4. I guess your diffusion model's version is the official OOTD diffusion model.
> > > In addition, if I solve your concern, can you give this project a **star**, thank you.
> > 
> > 
> > I wonder that if my diffusion model in "/OOTDiffusion/checkpoints/ootd/ootd_hd/checkpoint-36000/" should be the original Stable Diffusion_v1.5 model, but not the official OOTD diffusion model
> 
> yes , if you want to train your own model,you should use SDv1-5 model as model input.

Thanks for your reply, I will have a try though i'm also new to diffusion model used in virtual-try-on. I wanted to reproduce the OOTD work but i got no idea, maybe with your work, i can learn sth from it, thank a lot !

**Comment by GeneralWhite** [comment]
> > Hi, I see your problem. Please check out your diffusion model's version, it must be V1.5 or V1.4. I guess your diffusion model's version is the official OOTD diffusion model.
> > In addition, if I solve your concern, can you give this project a **star**, thank you.
> 
> I wonder that if my diffusion model in "/OOTDiffusion/checkpoints/ootd/ootd_hd/checkpoint-36000/" should be the original Stable Diffusion_v1.5 model, but not the official OOTD diffusion model

Thank you so much for your help

**Comment by GeneralWhite** [comment]
> Hi, I see your problem. Please check out your diffusion model's version, it must be V1.5 or V1.4. I guess your diffusion model's version is the official OOTD diffusion model.
> 
> In addition, if I solve your concern, can you give this project a **star**, thank you.

Thank you so much for your help :)
