### ISSUE TITLE
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. 

### ISSUE THREAD

**Issue by ManuelCecere** [lyc0929/OOTDiffusion-train#8]
Hi there, thank you for your work!

I'm trying to reproduce your results in a multi-gpu EC2 instance. I've run `accelerate configure` and launched the train script with `batch_size = 1` but I receive this error:
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument find_unused_parameters=True to torch.nn.parallel.DistributedDataParallel, and by
making sure all forward function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's forward function. Please include the loss function and the structure of the return value of forward of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 1: 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596 597 598 599 682 683 684 685
(This parameter indices are the same for every rank.)

I've tried to add `find_unused_parameters=True` using the handler in Accelerator:
```
accelerator = Accelerator(
    gradient_accumulation_steps=args.gradient_accumulation_steps,
    mixed_precision=args.mixed_precision,
    log_with=args.report_to,
    project_config=accelerator_project_config,
    kwargs_handlers=DistributedDataParallelKwargs(find_unused_parameters=True),
)
```

but it raise another error: `TypeError: 'DistributedDataParallelKwargs' object is not iterable`

Any idea on how to solve it?

**Comment by lyc0929** [comment]
I will update the code which supports multi-gpu soon

**Comment by ManuelCecere** [comment]
I was just looking at your last commit, and it seems that aggregating the two Unets in one class as you have done solves the problem.

```

class Unet_(torch.nn.Module):
    def __init__(self, vton_model, garm_model):
        super(Unet_, self).__init__()
        self.unet_vton = vton_model
        self.unet_garm = garm_model


unet_ = Unet_(unet_vton, unet_garm)

unet_, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
    unet_, optimizer, train_dataloader, lr_scheduler
)
```

Posting it here in case anyone is having the same issue ;-)
